# Generated by Django 3.0.5 on 2020-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0002_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
