# Generated by Django 3.0.5 on 2020-04-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('science', '0002_auto_20200430_2201'),
        ('medium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science.Article')),
            ],
        ),
        migrations.CreateModel(
            name='FrontMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Article')),
            ],
        ),
    ]
