# Generated by Django 3.0.5 on 2020-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_frontgallery_frontvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
