# Generated by Django 3.0.5 on 2020-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20200510_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
