# Generated by Django 3.0.5 on 2020-05-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_gallery_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
    ]
