# Generated by Django 3.0.5 on 2020-06-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20200523_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
